name: Generate and push image
on:
  workflow_dispatch:
  push:
    paths:
      - 'frp-latest-version.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      id-token: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        
      - name: login docker hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: login ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build the image
        run: |
          VERSION=$(<frp-latest-version.txt)
          echo $VERSION
          docker build ./frps -t zen8841/frpc:$VERSION
          docker build ./frpc -t zen8841/frpc:$VERSION
          
      - name: tag the image
        run: |
          docker image tag zen8841/frps:$VERION zen8841/frps:latest
          docker image tag zen8841/frpc:$VERION zen8841/frpc:latest
          docker image tag zen8841/frps:$VERSION ghcr.io/zen8841/frps:$VERSION
          docker image tag zen8841/frpc:$VERSION ghcr.io/zen8841/frpc:$VERSION
          docker image tag zen8841/frps:$VERSION ghcr.io/zen8841/frps:latest
          docker image tag zen8841/frps:$VERSION ghcr.io/zen8841/frps:latest

      - name: push image
        run: |
          docker push --all-tags zen8841/frps
          docker push --all-tags zen8841/frpc
          docker push --all-tags ghcr.io/zen8841/frps
          docker push --all-tags ghcr.io/zen8841/frpc
