name: Generate and push image
on:
  workflow_dispatch:
  push:
    paths:
      - 'frp-latest-version.txt'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "run ok"     
